apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: spire
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ghcr.io/spiffe/spire-agent:1.14.5
          command: ["/opt/spire/bin/spire-agent"]
          args: ["api", "watch", "-socketPath", "/run/spire/agent-sockets/spire-agent.sock"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/agent-sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
