apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.25.1
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "1"]
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket
          mountPath: /run/spire/agent-sockets
          readOnly: true          
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: docker.io/newzyer/symbank-webapp:latest
        command: ["/opt/symbank-webapp/symbank-webapp", "-config", "/run/symbank-webapp/config/symbank-webapp.conf"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: symbank-webapp-config
          mountPath: /run/symbank-webapp/config
      volumes:
      - name: envoy-config
        configMap:
          name: frontend-envoy
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
      - name: symbank-webapp-config
        configMap:
          name: symbank-webapp-config
